// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $consent from "./routes/consent.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $modules_name_ from "./routes/modules/[name].tsx";
import * as $modules_name_submodule_ from "./routes/modules/[name]/[submodule].tsx";
import * as $modules_name_review from "./routes/modules/[name]/review.tsx";
import * as $modules_index from "./routes/modules/index.tsx";
import * as $new_user from "./routes/new-user.tsx";
import * as $AudioPlayer from "./islands/AudioPlayer.tsx";
import * as $CheckboxMultiSelectQuestion from "./islands/CheckboxMultiSelectQuestion.tsx";
import * as $ContentCarousel from "./islands/ContentCarousel.tsx";
import * as $FileUploadQuestion from "./islands/FileUploadQuestion.tsx";
import * as $FillBlankQuestion from "./islands/FillBlankQuestion.tsx";
import * as $FreeFormQuestion from "./islands/FreeFormQuestion.tsx";
import * as $ImageGallery from "./islands/ImageGallery.tsx";
import * as $MobileMenu from "./islands/MobileMenu.tsx";
import * as $ModuleQuestionnaire from "./islands/ModuleQuestionnaire.tsx";
import * as $MultipleChoiceQuestion from "./islands/MultipleChoiceQuestion.tsx";
import * as $NoteQuestion from "./islands/NoteQuestion.tsx";
import * as $QuestionRenderer from "./islands/QuestionRenderer.tsx";
import * as $SubmoduleQuestionnaire from "./islands/SubmoduleQuestionnaire.tsx";
import * as $ThemeSwitcher from "./islands/ThemeSwitcher.tsx";
import * as $TrueFalseQuestion from "./islands/TrueFalseQuestion.tsx";
import * as $VideoPlayer from "./islands/VideoPlayer.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/consent.tsx": $consent,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
    "./routes/modules/[name].tsx": $modules_name_,
    "./routes/modules/[name]/[submodule].tsx": $modules_name_submodule_,
    "./routes/modules/[name]/review.tsx": $modules_name_review,
    "./routes/modules/index.tsx": $modules_index,
    "./routes/new-user.tsx": $new_user,
  },
  islands: {
    "./islands/AudioPlayer.tsx": $AudioPlayer,
    "./islands/CheckboxMultiSelectQuestion.tsx": $CheckboxMultiSelectQuestion,
    "./islands/ContentCarousel.tsx": $ContentCarousel,
    "./islands/FileUploadQuestion.tsx": $FileUploadQuestion,
    "./islands/FillBlankQuestion.tsx": $FillBlankQuestion,
    "./islands/FreeFormQuestion.tsx": $FreeFormQuestion,
    "./islands/ImageGallery.tsx": $ImageGallery,
    "./islands/MobileMenu.tsx": $MobileMenu,
    "./islands/ModuleQuestionnaire.tsx": $ModuleQuestionnaire,
    "./islands/MultipleChoiceQuestion.tsx": $MultipleChoiceQuestion,
    "./islands/NoteQuestion.tsx": $NoteQuestion,
    "./islands/QuestionRenderer.tsx": $QuestionRenderer,
    "./islands/SubmoduleQuestionnaire.tsx": $SubmoduleQuestionnaire,
    "./islands/ThemeSwitcher.tsx": $ThemeSwitcher,
    "./islands/TrueFalseQuestion.tsx": $TrueFalseQuestion,
    "./islands/VideoPlayer.tsx": $VideoPlayer,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
